version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_credenciamento
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: credenciamento_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    build: .
    container_name: nest_api_credenciamento
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: credenciamento_db
      JWT_SECRET: my-super-secret-key
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_USER: felipperabelodurans@gmail.com
      SMTP_PASSWORD: kamonrhxyugxjnxo
      SMTP_SECURE: true
      SMTP_LINK_QR_CODE: https://www.expomultimix.com/
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  mysql_data:
