version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_credenciamento
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backups:/backups
    command: --default-authentication-plugin=mysql_native_password

  api:
    build:
      context: .
      args:
        NODE_ENV: development
    container_name: nest_api_credenciamento
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  mysql_data:
  mysql_backups:
